name: Build Sakr Menu
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Theos
        uses: p0358/setup-theos@main
        with:
          theos-src: https://github.com/theos/theos.git

      - name: Build Tweak
        run: |
          make package FINALPACKAGE=1
        
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Sakr-Menu-Dylib
          path: packages/*.deb
