name: Build Tweak

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Theos
      uses: Randomblock1/theos-action@v1
      with:
        theos-sdks: https://github.com/theos/sdks
    
    - name: Build Tweak
      run: |
        export THEOS=/Users/runner/work/theos
        make clean
        make
    
    - name: Upload dylib
      uses: actions/upload-artifact@v4
      with:
        name: MUSTAFA_VIP
        path: .theos/obj/debug/*.dylib
